# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lucas Ezequiel Zamora
title: Senior Data Scientist
email: lucas.e.zamora@gmail.com
website: https://peepdata.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: lucaszamora10
github_username:  lezamora
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: lucas-zamora
# xing_username: jekyll
pinterest_username: lucasezamora
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Medium link
  icon: fab fa-medium
  url: https://medium.com/@lucasezamora
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Mi nombre es Lucas Zamora, <mark>Ingeniero en Sistemas de la Universidad Tecnológica Nacional (UTN)</mark> y profesional del mundo de los datos, más específicamente como <mark>Data Scientist</mark>. 

content:
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Clarín
        link: https://www.clarin.com/
        # link_text: boringcompany.com
        sub_title: Senior Data Scientist
        caption: Junio 2019 - Presente
        quote: >
          Mi trabajo es dar soporte a las distintas áreas de la empresa generando análisis, desarrollando modelos y reportes según las necesidades relevadas.
        description: | # this will include new lines to allow paragraphs
            Tareas desarrolladas:
            - Consulta, extracción y limpieza datos utilizado bases de datos SQL y NOSQL.
            - Utilización de Python y R para limpieza, análisis y visualización de datos.
            - Aplicación de pruebas estadísticas.
            - Construcción, evaluación e implementación de modelos de Machine Learning y Deep Learning (Scikit-Learn, Pytorch, Tensor Flow, etc).
            - Deploy a producción de estos modelos a través de REST APIs y aplicaciones (Python, Flask, Docker, etc.), y monitoreo de los mismos.
            - Web scraping.
            
      - layout: left
        title: Argenprop
        link: https://www.argenprop.com/
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: Julio 2018 - Junio 2019 
        quote: >
          En Argenprop principalmente fuí responsable del desarrollo de nuevas KPIs y de realicé análisis para dar respuestas a distintas problemáticas del negocio. 
        description: | # this will include new lines to allow paragraphs
            Tareas desarrolladas:
            - Consulta, extracción y limpieza datos utilizado bases de datos SQL y NOSQL.
            - Utilización de Python y R para limpieza, análisis y visualización de datos.
            - Web scraping.
            
      - layout: left
        title: Argenprop
        link: https://www.argenprop.com/
        # link_text: boringcompany.com
        sub_title: QA Automation
        caption: Diciembre 2016 - Julio 2018 
        quote: >
          En mi rol de QA fuí responsable del área de calidad de todos los portales pertenecientes a Argenprop.
        description: | # this will include new lines to allow paragraphs
            Responsable de calidad de un proyecto de Sancor Seguros, realizando las siguientes tareas:
              - Diseño y ejecución de casos de prueba automatizado utilizando Selenium WebDriver y C#.
              
      - layout: left
        title: IT Patagonia
        link: https://www.itpatagonia.com/
        # link_text: boringcompany.com
        sub_title: QA Automation
        caption: Julio 2016 - Diciembre 2016 
        quote: >
          Responsable de calidad de un proyecto de Sancor Seguros.
        description: | # this will include new lines to allow paragraphs
            Tareas desarrolladas:
              - Diseño y ejecución de casos de prueba automatizado utilizando Selenium WebDriver y C#.
              
      - layout: left
        title: Neoris
        link: https://www.neoris.com/
        # link_text: boringcompany.com
        sub_title: QA Analyst
        caption: Nobiembre 2014 - Julio 2016 
        quote: >
          Responsable de calidad de un proyecto perteneciente a Asociart Seguros.
        description: | # this will include new lines to allow paragraphs
            Tareas desarrolladas:
              - Diseño y ejecución de casos de prueba.             
  

  - title: Habilidades
    layout: text
    content: | # this will include new lines to allow paragraphs
      Además de las tareas desarrolladas tengo conociendo y experiencia en los siguientes campos:
        - Python
        - R
        - Docker
        - Power BI
        - SQL
        - NO SQL
        - Metodologías agíles
            

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UTN
        caption: 2012 - 2019
        sub_title: Ingeniería en Sistemas
        
content:
  - title: Projectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Blog
        link: https://peepdata.github.io/
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          Con el objetivo de compartir conocimiento creé un <mark>blog</mark> donde intento mostrar herramientas un poco fuera de lo común, donde no haya mucho material en español al respecto.
          
      - layout: top-middle
        title: Biblioteca de gráficos
        link: https://ar.pinterest.com/lucasezamora/storytelling-with-data-with-python-and-bokeh/
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          Recreé los gráficos recomendados por el libro Story telling with data (Wiley, 2015) con Python y Bokeh, y disponibilicé por medio de Pinterest y Github el código para recrearlo.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
